import { app, BrowserWindow, shell, dialog } from "electron";
import electronLocalShortcut from "electron-localshortcut";
import installExtension, {
  REACT_DEVELOPER_TOOLS,
} from "electron-extension-installer";
import { ipcMain } from "electron";
import {
  ConfigSchemaType,
  configStore,
  LocationsSchemaType,
  locationsStore,
  postalStore,
  SettingsSchemaType,
  settingsStore,
  CONFIG_VERSION,
  LOCATIONS_VERSION,
  SETTINGS_VERSION,
  POSTALS_VERSION,
  PostalsSchemaType,
  DEFAULT_SETTINGS,
  Ts3ServerProfile,
} from "./config";
import ElectronStore from "electron-store";
import * as fs from "fs";
import { updateElectronApp } from "update-electron-app";
import TS3ClientQuery from "./ts3ClientQuery";
import { parseNotifyTextMessage } from "./shared/utils/ts3ChannelList";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow | null = null;
let eventLogWindow: BrowserWindow | null = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// @ts-ignore
if (configStore.get("version") !== CONFIG_VERSION) {
  console.warn(
    "Config out of date, resetting to defaults. (version " +
      CONFIG_VERSION +
      ")"
  );
  // @ts-ignore
  configStore.clear();
}
// @ts-ignore
if (locationsStore.get("version") !== LOCATIONS_VERSION) {
  console.warn(
    "Locations out of date, resetting to defaults. (version " +
      LOCATIONS_VERSION +
      ")"
  );
  // @ts-ignore
  locationsStore.clear();
}
// @ts-ignore
if (postalStore.get("version") !== POSTALS_VERSION) {
  console.warn(
    "Postals out of date, resetting to defaults. (version " +
      POSTALS_VERSION +
      ")"
  );
  // @ts-ignore
  postalStore.clear();
}
// @ts-ignore
if (settingsStore.get("version") !== SETTINGS_VERSION) {
  // Never destructively clear settings on a version bump - that wipes
  // everything the user configured (API keys, channel IDs, sounds...)
  // back to shipped defaults. Instead, backfill only whatever's actually
  // missing, leaving every existing value untouched. This also runs
  // whenever a new field is added even without a version bump, so a
  // field like a new channel ID setting is never silently absent for
  // someone who already has a settings file from before it existed.
  console.log("[Settings] Schema updated - merging in any new fields, preserving existing values.");
  // @ts-ignore
  const current = (settingsStore.get("config") ?? {}) as Partial<typeof DEFAULT_SETTINGS>;
  const merged = { ...DEFAULT_SETTINGS, ...current };

  // ts3ServerProfiles needs its own per-profile merge (by index) so a
  // brand new per-server field, like civilianChannelId, gets backfilled
  // into each of the user's already-configured server profiles instead
  // of the whole array being replaced wholesale.
  if (Array.isArray(current.ts3ServerProfiles)) {
    merged.ts3ServerProfiles = DEFAULT_SETTINGS.ts3ServerProfiles.map(
      (defaultProfile: Ts3ServerProfile, i: number) => ({
        ...defaultProfile,
        ...(current.ts3ServerProfiles?.[i] ?? {}),
      })
    );
  }

  // @ts-ignore
  settingsStore.set("config", merged);
  // @ts-ignore
  settingsStore.set("version", SETTINGS_VERSION);
}

// if auto-updates are enabled, enable them
// @ts-ignore
const settings = settingsStore.get("config");
if (settings.autoUpdate) {
  updateElectronApp();
}

const createMainWindow = (): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 720,
    width: 1100,
    minHeight: 500,
    minWidth: 700,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Remove the default menu bar
  mainWindow.removeMenu();

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (process.env.NODE_ENV === "development") {
    // Open the DevTools.
    mainWindow.webContents.openDevTools();
  }

  return mainWindow;
};

const createEventLogWindow = (): BrowserWindow => {
  const win = new BrowserWindow({
    height: 500,
    width: 800,
    minHeight: 200,
    minWidth: 400,
    title: "Event Log",
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  win.removeMenu();
  win.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}?view=eventlog`);

  return win;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  if (process.env.NODE_ENV === "development") {
    await installExtension(REACT_DEVELOPER_TOOLS, {
      loadExtensionOptions: {
        allowFileAccess: true,
      },
    });
  }

  mainWindow = createMainWindow();

  // @ts-ignore
  if (settingsStore.get("config.stayOnTop") === true) {
    mainWindow.setAlwaysOnTop(true);
  }

  // Removing the default menu bar earlier also removed its built-in
  // "Toggle Developer Tools" shortcut, so it's registered here directly
  // instead, independent of any menu.
  electronLocalShortcut.register(mainWindow, "CmdOrCtrl+Shift+I", () => {
    mainWindow?.webContents.toggleDevTools();
  });

  // Poll for pending 911/311 calls from the main process, not the renderer -
  // Chromium throttles setInterval in unfocused/background windows, which
  // was causing alerts to be delayed until the dispatch panel regained
  // focus. The main process has no such throttling, so it stays reliable
  // even while the dispatcher is tabbed into TeamSpeak.
  let pendingPollInFlight = false;
  setInterval(async () => {
    if (!mainWindow || mainWindow.isDestroyed()) return;
    if (pendingPollInFlight) return; // previous check still running - skip this tick rather than overlap
    pendingPollInFlight = true;
    try {
      const client = getTs3Client();
      // @ts-ignore
      const profiles = settingsStore.get("config.ts3ServerProfiles") ?? [];
      const result = await client.getPendingCounts(profiles);
      mainWindow.webContents.send("ts3-pending-counts-push", result);
    } catch (err) {
      console.error("[TS3 pending-poll] failed:", err);
    } finally {
      pendingPollInFlight = false;
    }
  }, 2000);
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createMainWindow();
  }
});

const getStore = (
  store: string
): ElectronStore<
  | ConfigSchemaType
  | LocationsSchemaType
  | PostalsSchemaType
  | SettingsSchemaType
> => {
  if (store === "config") {
    return configStore;
  }
  if (store === "locations") {
    return locationsStore;
  }
  if (store === "postals") {
    return postalStore;
  }
  if (store === "settings") {
    return settingsStore;
  }
};

ipcMain.handle("electron-store-get", async (_, store, val) => {
  // @ts-ignore
  return getStore(store).get(val);
});
ipcMain.handle("electron-store-set", async (_, store, key, val) => {
  // @ts-ignore
  return getStore(store).set(key, val);
});
ipcMain.handle("reload", () => {
  mainWindow?.reload();
});
ipcMain.handle("open-config-dir", () => {
  shell.openPath(app.getPath("userData"));
});

ipcMain.handle("pick-sound-file", async () => {
  const result = await dialog.showOpenDialog({
    title: "Choose Alert Sound",
    filters: [{ name: "Audio Files", extensions: ["mp3", "wav", "ogg", "m4a"] }],
    properties: ["openFile"],
  });
  if (result.canceled || result.filePaths.length === 0) return null;
  return result.filePaths[0];
});

ipcMain.handle("backup-configuration", async () => {
  const result = await dialog.showSaveDialog({
    title: "Backup Configuration",
    defaultPath: `dispatch-panel-backup-${new Date().toISOString().slice(0, 10)}.json`,
    filters: [{ name: "CommsCenter Backup", extensions: ["json"] }],
  });
  if (result.canceled || !result.filePath) return { success: false, message: "Cancelled" };

  try {
    const backup = {
      backupVersion: 1,
      createdAt: new Date().toISOString(),
      // @ts-ignore
      config: configStore.get("config"),
      // @ts-ignore
      locations: locationsStore.get("config"),
      // @ts-ignore
      postals: postalStore.get("config"),
      // @ts-ignore
      settings: settingsStore.get("config"),
    };
    fs.writeFileSync(result.filePath, JSON.stringify(backup, null, 2), "utf-8");
    return { success: true, message: result.filePath };
  } catch (err) {
    return { success: false, message: (err as Error).message };
  }
});

ipcMain.handle("restore-configuration", async () => {
  const result = await dialog.showOpenDialog({
    title: "Restore Configuration",
    filters: [{ name: "CommsCenter Backup", extensions: ["json"] }],
    properties: ["openFile"],
  });
  if (result.canceled || result.filePaths.length === 0) return { success: false, message: "Cancelled" };

  const confirm = dialog.showMessageBoxSync({
    type: "warning",
    buttons: ["Cancel", "Restore"],
    defaultId: 0,
    cancelId: 0,
    title: "Restore Configuration",
    message: "This will overwrite your current channels, TeamSpeak profiles, sounds, and settings with the backup file. This cannot be undone. Continue?",
  });
  if (confirm !== 1) return { success: false, message: "Cancelled" };

  try {
    const raw = fs.readFileSync(result.filePaths[0], "utf-8");
    const backup = JSON.parse(raw);

    if (backup.config) {
      // @ts-ignore
      configStore.set("config", backup.config);
    }
    if (backup.locations) {
      // @ts-ignore
      locationsStore.set("config", backup.locations);
    }
    if (backup.postals) {
      // @ts-ignore
      postalStore.set("config", backup.postals);
    }
    if (backup.settings) {
      // @ts-ignore
      settingsStore.set("config", backup.settings);
    }

    mainWindow?.reload();
    return { success: true, message: "Restored" };
  } catch (err) {
    return { success: false, message: (err as Error).message };
  }
});

ipcMain.handle("open-event-log-window", () => {
  if (eventLogWindow && !eventLogWindow.isDestroyed()) {
    eventLogWindow.focus();
    return;
  }
  eventLogWindow = createEventLogWindow();
  eventLogWindow.addListener("closed", () => {
    eventLogWindow = null;
  });
});

ipcMain.handle("ts3-pending-counts", async () => {
  try {
    const client = getTs3Client();
    // @ts-ignore
    const profiles = settingsStore.get("config.ts3ServerProfiles") ?? [];
    const { counts, dispatcherPresent } = await client.getPendingCounts(profiles);
    return { success: true, counts, dispatcherPresent };
  } catch (err) {
    return { success: false, counts: {}, dispatcherPresent: {} };
  }
});

ipcMain.handle("ts3-caller-context", async () => {
  try {
    const client = getTs3Client();
    // @ts-ignore
    const profiles = settingsStore.get("config.ts3ServerProfiles") ?? [];
    const context = await client.getCallerContext(profiles);
    return { success: true, ...context };
  } catch (err) {
    return { success: false, status: "other" as const, label: "", callers: [] };
  }
});

ipcMain.handle("ts3-poke", async (_, clientId: string, message: string) => {
  try {
    const client = getTs3Client();
    return await client.pokeClient(clientId, message);
  } catch (err) {
    return { success: false, message: (err as Error).message, data: [] };
  }
});

ipcMain.handle("ts3-debug-clientlist", async () => {
  try {
    const client = getTs3Client();
    const clients = await client.getRawClientList();
    return { success: true, clients };
  } catch (err) {
    return { success: false, clients: [] };
  }
});

ipcMain.handle("ts3-list-civilians", async () => {
  try {
    const client = getTs3Client();
    // @ts-ignore
    const profiles = settingsStore.get("config.ts3ServerProfiles") ?? [];
    const civilians = await client.getAllCivilians(profiles);
    return { success: true, civilians };
  } catch (err) {
    return { success: false, civilians: [] };
  }
});

ipcMain.handle("ts3-move-civilian", async (_, targetClientId: string, buttonKey: string) => {
  try {
    const client = getTs3Client();
    // @ts-ignore
    const profiles = settingsStore.get("config.ts3ServerProfiles") ?? [];
    return await client.moveClientToButtonTarget(targetClientId, buttonKey as any, profiles);
  } catch (err) {
    return { success: false, message: (err as Error).message, data: [] };
  }
});

let ts3ClientQuery: TS3ClientQuery | null = null;
const getTs3Client = (): TS3ClientQuery => {
  // @ts-ignore
  const apiKey: string = settingsStore.get("config.ts3ClientQueryApiKey") ?? "";
  if (!ts3ClientQuery) {
    ts3ClientQuery = new TS3ClientQuery(apiKey);
    ts3ClientQuery.onNotification = (line: string) => {
      if (!mainWindow || mainWindow.isDestroyed()) return;
      if (line.startsWith("notifytextmessage")) {
        const parsed = parseNotifyTextMessage(line);
        if (parsed) {
          // @ts-ignore
          const ignoredSender: string = settingsStore.get("config.ignoredMessageSender") ?? "";
          const isIgnored =
            ignoredSender.trim() !== "" &&
            parsed.sender.trim().toLowerCase() === ignoredSender.trim().toLowerCase();
          if (!isIgnored) {
            mainWindow.webContents.send("ts3-message-received", { ...parsed, timestamp: new Date().toISOString() });
          }
          return;
        }
      }
      // Anything else unrecognized - log it so we can identify what event
      // name actually carries incoming pokes, if this app ever needs to
      // distinguish them from regular messages.
      console.log("[TS3 notification - unhandled]", line);
    };
  } else {
    ts3ClientQuery.setApiKey(apiKey);
  }
  return ts3ClientQuery;
};

ipcMain.handle("ts3-move", async (_, buttonKey: string) => {
  try {
    const client = getTs3Client();
    // @ts-ignore
    const profiles = settingsStore.get("config.ts3ServerProfiles") ?? [];
    return await client.moveToButtonTarget(buttonKey as any, profiles);
  } catch (err) {
    return { success: false, message: (err as Error).message, data: [] };
  }
});

ipcMain.handle("ts3-channellist", async () => {
  try {
    const client = getTs3Client();
    return await client.listChannels();
  } catch (err) {
    return { success: false, message: (err as Error).message, data: [] };
  }
});
